# This is the default submit config
[meta]
version = "1.0"

# iverilog
[iv_config]
commit_info = "iv"

# verilator
[ver_config]
commit_info = "ver"

# vcs+dc
[soc_config]
commit_info = "soc"
type = "vcs+dc" # [vcs, dc, vcs+dc, wave]
prog = 'all' # format: [prog]-[type] prog: [hello, memtest, rtthread] type: [flash, mem, sdram]
freq = 100 # [100, 800, step: 50]
