# This is the default submit config
[meta]
version = "1.0"

# [iv_config]
# trigger = "iverilog"
# [ver_config]
# trigger = "verilator"

[soc_config]
trigger = "cicd"
type = "vcs & dc" # [vcs, dc, vcs & dc, wave]
freq = 100 # [100, 800]
